const ORTE = [

  {
    name: "CHUWOO",
    kiez: "Mitte",
    maps: "https://maps.app.goo.gl/t5nk5V3Ybbptj85H9",
    kommentar: "Kleines Restaurant mit wenigen Tischen, aber genau das macht es aus. Die Kuche bietet chinesische Spezialitaten die man in Berlin kaum findet. Nicht verpassen: die besondere Dessertauswahl. Einrichtung verspielt und liebevoll.",
    kueche: "Chinesisch / Asiatisch",
    tageszeit: ["lunch", "dinner"],
    vibe: ["schnell", "lebendig"],
    budget: "mid",
    vegan: true,
    reservierung: false,
    walkin: true,
    cashonly: false,
  },
  
  {
    name: "Banh Mi Stable",
    kiez: "Mitte",
    maps: "https://maps.app.goo.gl/scEYY2PbqpS4YRtH6",
    kommentar: "Kleiner Laden, perfekt für einen schnellen vietnamesischen Snack. Hauptsächlich Banh Mi Sandwiches. Favorit: Banh Mi Heo Quay",
    kueche: "Vietnamesisch",
    tageszeit: ["lunch", "dinner"],
    vibe: ["schnell"],
    budget: "low",
    vegan: false,
    reservierung: false,
    walkin: true,
    cashonly: true,
  },
  
  {
    name: "Ming Dynastie Jannowitzbrücke",
    kiez: "Mitte",
    maps: "https://maps.app.goo.gl/cc7xpBMcuQzWHEvV6",
    kommentar: "Restaurant mit viel Platz und klassisch chinesischer Einrichtung, was direkt für eine authentische Atmosphäre sorgt. Die Nähe zur chinesischen Botschaft unterstreicht das Ganze noch. Mittags gibt es ein Menüangebot. Besonders schön: die Lage direkt am Wasser.",
    kueche: "Chinesisch",
    tageszeit: ["lunch", "dinner"],
    vibe: ["besonders","lebendig"],
    budget: "mid",
    vegan: true,
    reservierung: true,
    walkin: true,
    cashonly: false,
  },
  {
    name: "Coccodrillo",
    kiez: "Mitte",
    maps: "https://maps.app.goo.gl/WMoVs9E2V637gsDd7",
    kommentar: "Stilvolles italienisches Restaurant mit außergewöhnlicher Einrichtung, das direkt für ein besonderes Ambiente sorgt. Die Küche bietet klassische italienische Gerichte, wobei vor allem die Vorspeisen überzeugen, besonders Stracciatella und frittierte Lasagne (wechselnde Karte). Die Trüffelpasta ist das klare Highlight. Die Pizza fällt preislich etwas ab. Insgesamt etwas teurer, aber das Erlebnis lohnt sich, früh reservieren.",
    kueche: "Italienisch",
    tageszeit: ["lunch", "dinner"],
    vibe: ["besonders","lebendig"],
    budget: ["mid", "high"],
    vegan: true,
    reservierung: true,
    walkin: false,
    cashonly: false,
  },

  {
    name: "Inari-San Berlin",
    kiez: "Mitte",
    maps: "https://maps.app.goo.gl/51qgykzvxX26UNVGA",
    kommentar: "Kleiner Laden, eher für to go gedacht, mit ein paar Bänken draußen zum schnellen Essen. Auf Inaris spezialisiert. Der Matcha wird frisch zubereitet und überzeugt. Etwas teurer, aber die Qualität passt. Nur Kartenzahlung. Favorit: Inari Bake, Yuzu Salmon",
    kueche: "Japanisch",
    tageszeit: ["lunch", "dinner"],
    vibe: ["schnell","unkompliziert"],
    budget: "mid",
    vegan: true,
    reservierung: false,
    walkin: true,
    cashonly: false,
  },

];
