const ORTE = [

  {
    name: "Katz Orange",
    kiez: "Mitte",
    maps: "https://maps.app.goo.gl/KatzOrange",
    kommentar: "Versteckter Innenhof, saisonale Küche. Fühlt sich an wie bei jemandem zu Hause, nur besser gekocht. Unbedingt reservieren.",
    kueche: "Deutsch / Saisonal",
    tageszeit: ["dinner"],
    vibe: ["entspannt", "besonders"],
    budget: "mid",
    vegan: false,
    reservierung: true,
    walkin: false,
    cashonly: false,
  },

  {
    name: "Doyum Grillhaus",
    kiez: "Kreuzberg",
    maps: "https://maps.app.goo.gl/Doyum",
    kommentar: "Kein Schnickschnack. Bestes Adana-Kebab in Kreuzberg, seit Jahrzehnten. Einfach hingehen.",
    kueche: "Türkisch",
    tageszeit: ["lunch", "dinner"],
    vibe: ["schnell", "lebendig"],
    budget: "low",
    vegan: false,
    reservierung: false,
    walkin: true,
    cashonly: true,
  },

  {
    name: "Silo Coffee",
    kiez: "Friedrichshain",
    maps: "https://maps.app.goo.gl/SiloCoffee",
    kommentar: "Top Specialty-Coffee und dicke Brunchplatten. Lassige Atmosphare, gute Energie. Wochenends voll, unter der Woche entspannter.",
    kueche: "Cafe / Brunch",
    tageszeit: ["brunch"],
    vibe: ["entspannt", "lebendig"],
    budget: "mid",
    vegan: true,
    reservierung: false,
    walkin: true,
    cashonly: false,
  },

  {
    name: "Nobelhart und Schmutzig",
    kiez: "Mitte",
    maps: "https://maps.app.goo.gl/Nobelhart",
    kommentar: "Brutal local. Nur Zutaten aus Brandenburg. Eines der besten Restaurants Berlins, fur Abende die man nicht vergisst.",
    kueche: "Fine Dining / Regional",
    tageszeit: ["dinner"],
    vibe: ["besonders"],
    budget: "high",
    vegan: false,
    reservierung: true,
    walkin: false,
    cashonly: false,
  },

  {
    name: "CHUWOO",
    kiez: "Mitte",
    maps: "https://maps.app.goo.gl/t5nk5V3Ybbptj85H9",
    kommentar: "Kleines Restaurant mit wenigen Tischen, aber genau das macht es aus. Die Kuche bietet chinesische Spezialitaten die man in Berlin kaum findet. Nicht verpassen: die besondere Dessertauswahl. Einrichtung verspielt und liebevoll.",
    kueche: "Chinesisch / Asiatisch",
    tageszeit: ["lunch", "dinner"],
    vibe: ["schnell", "lebendig"],
    budget: "mid",
    vegan: true,
    reservierung: false,
    walkin: true,
    cashonly: false,
  },
  {
    name: "Banh Mi Stable",
    kiez: "Mitte",
    maps: "https://maps.app.goo.gl/scEYY2PbqpS4YRtH6",
    kommentar: "Kleiner Laden, perfekt für einen schnellen vietnamesischen Snack. Hauptsächlich Banh Mi Sandwiches. Favorit: Banh Mi Heo Quay",
    kueche: "Vietnamesisch",
    tageszeit: ["lunch", "dinner"],
    vibe: ["schnell"],
    budget: "low",
    vegan: false,
    reservierung: false,
    walkin: true,
    cashonly: true,
  },
  {
    name: "Ming Dynastie Jannowitzbrücke",
    kiez: "Mitte",
    maps: "https://maps.app.goo.gl/cc7xpBMcuQzWHEvV6",
    kommentar: "Restaurant mit viel Platz und klassisch chinesischer Einrichtung, was direkt für eine authentische Atmosphäre sorgt. Die Nähe zur chinesischen Botschaft unterstreicht das Ganze noch. Mittags gibt es ein Menüangebot. Besonders schön: die Lage direkt am Wasser.",
    kueche: "Chinesisch",
    tageszeit: ["lunch", "dinner"],
    vibe: ["besonders",lebendig],
    budget: "mid",
    vegan: true,
    reservierung: true,
    walkin: true,
    cashonly: false,
  },

];
