const ORTE = [

  {
    name: "CHUWOO",
    kiez: "Mitte",
    maps: "https://maps.app.goo.gl/t5nk5V3Ybbptj85H9",
    kommentar: "Kleines Restaurant mit wenigen Tischen, aber genau das macht es aus. Die Kuche bietet chinesische Spezialitaten die man in Berlin kaum findet. Nicht verpassen: die besondere Dessertauswahl. Einrichtung verspielt und liebevoll.",
    kueche: "Chinesisch / Asiatisch",
    tageszeit: ["lunch", "dinner"],
    vibe: ["schnell", "lebendig"],
    budget: ["mid"],
    vegan: true,
    reservierung: false,
    walkin: true,
    cashonly: false,
  },
  
  {
    name: "Bánh mì Sài Gòn",
    kiez: "Mitte",
    maps: "https://maps.app.goo.gl/kQ71sXPaWJkHwRig6",
    kommentar: "Vietnamesisches Baguette - Kleiner Laden, perfekt für einen schnellen vietnamesischen Snack. Hauptsächlich Banh Mi Sandwiches. Favorit: Banh Mi Heo Quay",
    kueche: "Vietnamesisch",
    tageszeit: ["lunch", "dinner"],
    vibe: ["schnell"],
    budget: ["low"],
    vegan: false,
    reservierung: false,
    walkin: true,
    cashonly: true,
  },
  
  {
    name: "Ming Dynastie Jannowitzbrücke",
    kiez: "Mitte",
    maps: "https://maps.app.goo.gl/cc7xpBMcuQzWHEvV6",
    kommentar: "Restaurant mit viel Platz und klassisch chinesischer Einrichtung, was direkt für eine authentische Atmosphäre sorgt. Die Nähe zur chinesischen Botschaft unterstreicht das Ganze noch. Mittags gibt es ein Menüangebot. Besonders schön: die Lage direkt am Wasser.",
    kueche: "Chinesisch",
    tageszeit: ["lunch", "dinner"],
    vibe: ["besonders","lebendig"],
    budget: ["mid"],
    vegan: true,
    reservierung: true,
    walkin: true,
    cashonly: false,
  },
  {
    name: "Coccodrillo",
    kiez: "Mitte",
    maps: "https://maps.app.goo.gl/WMoVs9E2V637gsDd7",
    kommentar: "Stilvolles italienisches Restaurant mit außergewöhnlicher Einrichtung, das direkt für ein besonderes Ambiente sorgt. Die Küche bietet klassische italienische Gerichte, wobei vor allem die Vorspeisen überzeugen, besonders Stracciatella und frittierte Lasagne (wechselnde Karte). Die Trüffelpasta ist das klare Highlight. Die Pizza fällt preislich etwas ab. Insgesamt etwas teurer, aber das Erlebnis lohnt sich, früh reservieren.",
    kueche: "Italienisch",
    tageszeit: ["lunch", "dinner"],
    vibe: ["besonders","lebendig"],
    budget: ["mid", "high"],
    vegan: true,
    reservierung: true,
    walkin: false,
    cashonly: false,
  },

  {
    name: "Inari-San Berlin",
    kiez: "Mitte",
    maps: "https://maps.app.goo.gl/51qgykzvxX26UNVGA",
    kommentar: "Kleiner Laden, eher für to go gedacht, mit ein paar Bänken draußen zum schnellen Essen. Auf Inaris spezialisiert. Der Matcha wird frisch zubereitet und überzeugt. Etwas teurer, aber die Qualität passt. Nur Kartenzahlung. Favorit: Inari Bake, Yuzu Salmon",
    kueche: "Japanisch",
    tageszeit: ["lunch", "dinner"],
    vibe: ["schnell","entspannt"],
    budget: ["mid"],
    vegan: true,
    reservierung: false,
    walkin: true,
    cashonly: false,
  },
  
  {
  name: "The Bun Society",
  kiez: "Kreuzberg",
  maps: "https://maps.app.goo.gl/XJE3rQw82ca6kU2N6",
  kommentar: "Ein kleines Imbiss-Restaurant mit stilvoller, minimalistischer Einrichtung und nur wenigen Tischen. Reservierungen sind nicht möglich, Tischservice gibt es keinen – Paare und kleine Gruppen sind hier am besten aufgehoben. Die wechselnde Karte bietet besondere, sehr leckere Burger, wobei der Sumac Slap Burger das absolute Highlight ist. Als Dessert gibt es eine Auswahl ungewöhnlicher Eissorten wie Matcha oder Mango Sticky Rice.", 
  kueche: "Smashburger / Asian-American",
  tageszeit: ["lunch", "dinner"],
  vibe: ["entspannt"],
  budget: ["low", "mid"],
  vegan: true,
  reservierung: false, 
  walkin: true,
  cashonly: false, 
},
  
  {
  name: "Oregano Pizza & Pasta",
  kiez: "Kreuzberg",
  maps: "https://maps.app.goo.gl/mtcGQXohDoBPa9d16",
  kommentar: "Ein im Kiez bestens bekannter und beliebter Imbiss – klein, mit nur zwei bis drei Tischen und klar auf das Mitnehmen ausgerichtet. Die Preise sind günstig, die Pizza und Pasta überzeugen. Ein besonderer Favorit: die Pasta Carbonara.",
  kueche: "Italienisch / Pizza & Pasta",
  tageszeit: ["lunch", "dinner"],
  vibe: ["entspannt", "schnell"],
  budget: ["low"],
  vegan: true,
  reservierung: false,
  walkin: true,
  cashonly: false,
},

  {
  name: "Little Little Chinese Dumpling",
  kiez: "Charlottenburg",
  maps: "https://maps.app.goo.gl/p3zy8TNgJeU2qCPt5",
  kommentar: "Authentisch chinesische Küche mit einer tollen Auswahl an Speisen – besonders hervorzuheben sind die hausgemachten Dumplings. Das Restaurant ist gut besucht, eine kurze Wartezeit sollte man einplanen. Das absolute Highlight: der Dumpling Mix.",
  kueche: "Chinesisch / Dumplings & Bao",
  tageszeit: ["lunch", "dinner"],
  vibe: ["entspannt"],
  budget: ["low","mid"],
  vegan: true,
  reservierung: false,
  walkin: false,
  cashonly: false,
},

];
